typography_spectrum: 0.6244942895136774
color:
  brandStrength: 0.460702475393191
  lightness: 0.4730800816323608
  saturation: 0.547069986583665
  rhythmicContrast: 0.587783930124715
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.23497436358593404
name: Fact&Fiction
navigation:
  - name: Social Media
    url: 'https://twitter.com/SandraLukosiut1'
    type: external
title: FACT&FICTION
description: SANDRA LUKOSIUTE
